---
- name: Create a password for user
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Create a password for user debian
      user:
        name: debian
        password: '55dedd5adf3b7641f457b2c94d93f590c3e952de4635a1f832facd0564f75a1a87e50b32e58ffad8e2508f6155f057dc5eed58c1ca615a73b1a13cc7f8df8761'
