---
- name: Create a password for user
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Create a password for user ubuntu
      user:
        name: ubuntu
        password: '$6$rounds=4096$QwsXESlF0BQB00sG$oKVvGc5d4kdJDuCS2N4t/lxXa5OOpOj7/u5zDTDp45oGNamUhRO0EbjjEjFBnqMlI1zQ0Rwlt.XYHA/mnVQRM0'
  
